# Generated by Django 5.1.7 on 2025-04-29 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0002_initial'),
        ('consultation_management', '0003_consultation_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='appointment_management.center'),
        ),
    ]
